---
# Handler actions

- name: Restart Fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Restart yum-cron
  service:
    name: yum-cron
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

