---
# Tasks for bu_node_install_nodes

- name: (bu_node_install_nodes) [1/5] Bitcoin user is present
  user:
    name: bitcoin
    uid: 8331

- name: (bu_node_install_nodes) [2/5] Bitcoin conf dirs are present
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  with_items:
    - { path: '/home/bitcoin/.bitcoin', user: bitcoin }
    - { path: '/root/.bitcoin', user: root }

# bitcoinunlimited.info was undergoing a DDoS attack when writing this, and
# /u/s1ckpig informed me that github mirrors all the releases. So if this fails,
# we can safely skip it and get the one from github
- name: (bu_node_install_nodes) [3/5] Bitcoin Unlimited files are downloaded from bitcoinunlimited.info
  get_url:
    url: https://www.bitcoinunlimited.info/components/bitcoin-unlimited-web-downloads/bitcoinUnlimited-1.0.1.1-linux64.tar.gz
    dest: /opt/bitcoinUnlimited-1.0.1.1.tar.gz
    remote_src: True
  register: result
  ignore_errors: yes

- name: (bu_node_install_nodes) [3/5] Bitcoin Unlimited files are downloaded from github
  get_url:
    url: https://github.com/BitcoinUnlimited/BitcoinUnlimitedWebDownloads/raw/master/bitcoinUnlimited-1.0.1.1-linux64.tar.gz
    dest: /opt/bitcoinUnlimited-1.0.1.1.tar.gz
    remote_src: True
  when: result|failed

- name: (bu_node_install_nodes) [4/5] Bitcoin Unlimited files are unpacked
  unarchive:
    src: /opt/bitcoinUnlimited-1.0.1.1.tar.gz
    dest: /opt/
    copy: no

- name: (bu_node_install_nodes) [5/5] Bitcoin Unlimited files are deployed
  synchronize:
    src: /opt/bitcoinUnlimited-1.0.1/
    dest: /usr/
  delegate_to: "{{ inventory_hostname }}"
