---
# roles/httpd/defaults/main.yml

################################################################################### CHANGE ME

httpd_webservice: webservice

httpd_ServerAdmin: root@localhost

httpd_LoadModules:
  - alias
  - dir
  - logio
  - log_config
  - mime
  - mime_magic
  - rewrite

httpd_LogLevel: warn

httpd_DocumentRoot: /var/www

## SSL Cert
httpd_ssl_cert_country: US
httpd_ssl_cert_state: OH
httpd_ssl_cert_locality: Columbus

################################################################################### SANE DEFAULTS

httpd_ssl_cert_common_name: "{{ ansible_domain }}"
httpd_ssl_cert_subj_string: "/C={{ httpd_ssl_cert_country }}/ST={{ httpd_ssl_cert_state }}/L={{ httpd_ssl_cert_locality }}/CN={{ httpd_ssl_cert_common_name }}"
httpd_ssl_cert_days: 3650

httpd_config_file: '/etc/httpd/conf/httpd.conf'

# Scripting support
httpd_scripting: 'none'

httpd_tls_enforce: true

# Main configuration
httpd_ServerRoot: '/etc/httpd'
httpd_Listen: 80
httpd_ServerTokens: Prod

httpd_ErrorLog: logs/error_log
httpd_AccessLog: logs/access_log

httpd_Listen_ssl: 443

httpd_ServerName: "{{ ansible_domain }}"
#
httpd_ErrorLog_ssl: logs/ssl_error_log
httpd_AccessLog_ssl: logs/ssl_access_log
httpd_LogLevel_ssl: warn
#
httpd_SSLCertificateFile:  /etc/httpd/ssl/apache.pem
httpd_SSLCertificateKeyFile: /etc/httpd/ssl/apache.key
#
## According to:
## https://mozilla.github.io/server-side-tls/ssl-config-generator/
httpd_SSLProtocol: 'all -SSLv3 -TLSv1'
httpd_SSLCipherSuite: 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK'
httpd_SSLHonorCipherOrder: 'on'

