---
# IPTables Installation

- name: (iptables_install) [1/4] Firewalld is stopped
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: (iptables_install) [2/4] iptables is installed
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ iptables_packages }}"
  register: iptables_new_install

- name: (iptables_install) [3/4] libselinux-python is installed
  package:
    name: libselinux-python
    state: latest
  when: iptables_new_install.changed

- name: (iptables_install) [4/4] SELinux is disabled for iptables config
  selinux:
    state: disabled
  when: iptables_new_install.changed
